### ISSUE TITLE
Package DLMg to exe

### ISSUE THREAD

**Issue by hokiespurs** [OSU-Geomatics/OregonState_DLM#6]
Pyinstaller throws error when packaging pyqtgraph
### main.py

``` python
#main.py
import pyqtgraph.examples as p
p.run()
```
### makeEXE.bat

```
pyinstaller --onefile --debug main.py
```
### Error

```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\users\richie\appdata\local\temp\pip-build-dqvex_\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 68, in <module>
  File "site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
Failed to execute script pyi_rth_pkgres
```

**Comment by hokiespurs** [comment]
Need to try using py2exe (apparently much better for pyqtgraph versions 0.9.8 and beyond)
[Example Documentation on how to make it work](http://www.pyqtgraph.org/Bundling%20applications%20with%20PyQtGraph_R16.pdf)

**Comment by hokiespurs** [comment]
done.  Needed to download development branch of pyinstaller
